alsa-project/alsa-gobject

- src/ctl/elem-info-int.c
ALSACtl::ElemInfoInt has properties for 'min', 'max' and 'step' but their
assignments are not proper. This commit fixes the bug.
Fixes: aac870451a89 ("ctl: elem_info_int: add properties for type-dependent parameters and constructor")
> ctl: elem_info_int: fix wrong assignment to private value

- src/ctl/alsactl.map
- src/ctl/elem-id.c
- src/ctl/elem-id.h
- src/ctl/elem-value.c
- src/ctl/elem-value.h
- tests/alsactl-elem-id
- tests/alsactl-elem-value
For some cases, it's convenient for users to check whether two instances of elem_id/elem_value have the same meaning. In glib, APIs for comparison of content of objects are named as equal. This commit adds equal APIs for this purpose.
> ctl: elem_id/elem_value: add APIs to check whether two instances have the same meaning

- doc/reference/ctl/alsactl.types
- src/ctl/alsactl-enum-types.h
- src/ctl/alsactl.map
- src/ctl/card.c
- src/ctl/card.h
- tests/alsactl-enums
This patchset incldues two changes:
* rename element event flag with suitable name
* simplify event dispatching
> ctl: misc fixes

- src/ctl/elem-value.c
The 'snd_ctl_elem_value' structure includes union member for values.
Although it includes 'enumerated' member for values in enumerated type
of element, current implementation of alsactl library uses 'integer'
member to pick up the values. As a result, in any 64 bit System V ABI,
the library fails to get/set values for the enumerated type of
element. This commit fixes the bug.
> alsa-gobject: ctl: fix wrong operation for values in enumerated type of element

- .github/workflows/build.yml
Even if any pull request is triggered, in 'build_in_ubuntu_on_lxd' job
of 'Build test' workflow, upstream repository is cloned and requested
git hash is checked out. However this fails because the hash is in
requested repository.
This commit fixes the workflow so that requested repository is cloned.
Fixes: 8cb6715aab65 ('Add support workflow of Github Actions')
> alsa-gobject: fix workflow of Github Actions to clone requested repository

- src/ctl/card.c
- src/ctl/card.h
- src/timer/user-instance.c
- src/timer/user-instance.h
As long as using the created Gsource with GMainContext, the call of poll(2)
system call with infinite timeout surely returns when quit() method is
called for the context. All of GMainContext implements GWakeup with eventfd
and the call of quit() emits event via the file descriptor of eventfd. This
brings wakeup from blocking when poll(2) is called with inifinite timeout.
In current implementation of alsactl/alsatimer, open(2) is called with O_NONBLOCK
and GSource includes explicit timeout to avoid the infinite blocking. However,
they are not necessarily required for GMainContext.
This patchset obsoletes these points and adds options as the alternatives.
> alsa-gobject: GSource optimization

- .github/workflows/build.yml
In lxd repository for Ubuntu Cloud Images[1], Ubuntu i386 container
is available for applications of Intel386 ABI.
This commit uses the container to test build for Intel386 ABI in
workflow of Github Actions.
I note that no official Fedora i386 container is in dockerhub
registry[2]. It's needed to find the way to build application for
Intel386 ABI on AMD64 architecture (perhaps multiarch) if we are
going to support it.
[1] https://cloud-images.ubuntu.com/releases/
[2] https://hub.docker.com/_/fedora
> alsa-gobject: add support for i386 build job to workflow of Github Actions

- src/seq/alsaseq.map
- src/seq/event-data-connect.c
- src/seq/event-data-connect.h
- src/seq/event-data-ctl.c
- src/seq/event-data-ctl.h
- src/seq/event-data-note.c
- src/seq/event-data-note.h
- src/seq/event-data-queue.c
- src/seq/event-data-queue.h
- src/seq/event-data-result.c
- src/seq/event-data-result.h
- src/seq/event-fixed.c
- src/seq/event-fixed.h
- src/seq/tstamp.c
- src/seq/tstamp.h
The alsa-gobject project has a loose convention to have functions returning nothing. This pull
request refine according to it as well as fixes for some bugs.
> alsa-gobject: normalize function signatures

- src/ctl/elem-id.c
- src/ctl/elem-info-bool.c
- src/ctl/elem-info-bytes.c
- src/ctl/elem-info-enum.c
- src/ctl/elem-info-iec60958.c
- src/ctl/elem-info-int.c
- src/seq/addr.c
- src/seq/event-fixed.c
- src/seq/event-variable.c
- src/seq/subscribe-data.c
- src/timer/device-id.c
Some constructor functions have redundant or invalid annotations.
> alsa-gobject: fix annotations for constructors

- src/seq/event-data-queue.c
- src/seq/event-fixed.c
- src/seq/event.c
- src/seq/queue-status.c
- src/seq/queue-status.h
- src/seq/tstamp.c
- src/seq/tstamp.h
In UAPI for ALSA Sequencer, snd_seq_timestamp is union with
snd_seq_tick_time_t and struct snd_seq_real_time types. The
libalsaseq has GLib Boxed object for the union, named as
ALSASeqTstamp.
```
$ cat build/src/seq/ALSASeq-0.0.gir
...
<union name="Tstamp"
c:type="ALSASeqTstamp"
glib:type-name="ALSASeqTstamp"
glib:get-type="alsaseq_tstamp_get_type"
c:symbol-prefix="tstamp">
<source-position filename="../src/seq/tstamp.h" line="14"/>
...
</union>
...
```
Although this is valid in a view of GObject
Introspection, it's not necessarily convenient to language
bindings because some programming language doesn't support
union type. In this case, the type is not available.
This commit adds an alternative structure to wrap the union.
As a result, ALSASeqTstamp is GLib Boxed object for the
wrapper …
> alsa-gobject: seq: tstamp: use wrapper structure instead of union

- src/seq/addr.c
- src/seq/addr.h
- src/seq/alsaseq.map
- src/seq/event-data-queue.c
- src/seq/event-data-queue.h
- src/seq/event-fixed.c
- src/seq/event-fixed.h
- src/seq/queue-tempo.c
- src/seq/queue-tempo.h
- src/seq/tstamp.c
- src/seq/tstamp.h
- src/seq/user-client.c
- src/seq/user-client.h
In UAPI of ALSA Sequencer, some members in structures are defined as
fixed-sized array. For accessor methods to the members, this patchset
adds changes so that function annotations have 'not a variable length
array type' in their prototype.
In some cases, it's convenient to compare two instance of ALSASeq.Addr.
This patchset adds a new API, 'ALSASeq.Addr.equal()' for this purpose.
Finally, this patchset also adds some improvements and fixes.
> alsa-gobject: seq: some improvements and fixes

- src/seq/event-data-queue.c
- src/seq/event-fixed.c
- src/seq/event.c
- src/seq/tstamp.c
- src/seq/tstamp.h
This reverts commit 20fdc2d893ccba609cc786ebac733bf6914f9874.
In the above commit, union type structure is wrapped with care of
language bindings in which union-compatible feature is not expected.
However, it's responsible for language bindings to parse gir and
the care is not necessarily required in shared library side. In first
place, ALSASeq.Tstamp is boxed type object.
> alsa-gobject: seq: Revert "seq: tstamp: use wrapper structure instead of union"

- src/seq/user-client.c
- src/seq/user-client.h
The 'port_id' parameters of 'alsaseq_user_client_create_port()' is
a pointer to storage of unsigned char type, due to optional parameter
in g-i interface. It's read-only if having value and it's better to
have const qualifier.
> seq: user_client: use constant qualifier for read-only parameter

- src/seq/user-client.c
- src/seq/user-client.h
In implementation of ALSA sequencer core, the port owned by client can
be deleted by userspace applications which opens the client, therefore
it's necessary and sufficient to have an argument just for the numerical
ID of port.
This commit removes the useless argument for port information.
> alsa-gobject: seq: user_client: remove useless argument of delete_port()

- doc/reference/ctl/alsactl-docs.xml
- src/ctl/card-info.c
- src/ctl/card.c
- src/ctl/elem-id.c
- src/ctl/elem-info-bool.c
- src/ctl/elem-info-bytes.c
- src/ctl/elem-info-enum.c
- src/ctl/elem-info-iec60958.c
- src/ctl/elem-info-int.c
- src/ctl/elem-info-int64.c
- src/ctl/elem-info.c
- src/ctl/elem-value.c
- src/ctl/query.c
This patch fulfills alsactl documentation for GObject-derived objects and boxed objects.
> alsa-gobject: ctl: fulfill documentation for ALSACtl

- doc/reference/ctl/alsactl-docs.xml
- doc/reference/hwdep/alsahwdep-docs.xml
- doc/reference/rawmidi/alsarawmidi-docs.xml
- doc/reference/timer/alsatimer-docs.xml
- src/ctl/card-info.c
- src/ctl/card.c
- src/ctl/elem-id.c
- src/ctl/elem-info.c
- src/ctl/elem-value.c
- src/ctl/query.c
- src/hwdep/device-info.c
- src/hwdep/query.c
- src/rawmidi/query.c
- src/rawmidi/stream-pair.c
- src/rawmidi/substream-info.c
- src/rawmidi/substream-params.c
- src/rawmidi/substream-status.c
- src/timer/device-id.c
- src/timer/device-info.c
- src/timer/device-params.c
- src/timer/device-status.c
- src/timer/event-data-tick.c
- src/timer/event-data-timestamp.c
- src/timer/event-data.c
- src/timer/instance-info.c
- src/timer/instance-params.c
- src/timer/instance-status.c
- src/timer/query.c
- src/timer/user-instance.c
This patchset fulfills documentation for ALSAHwdep/ALSATimer/ALSARawmidi, except for ALSASeq, including some documentation improvements for ALSACtl.
> alsa-gobject: hwdep/timer/rawmidi: fulfill documentation for ALSAHwdep/ALSATimer/ALSARawmidi

- doc/reference/seq/alsaseq-docs.xml
- src/seq/addr.c
- src/seq/client-info.c
- src/seq/client-pool.c
- src/seq/event-data-connect.c
- src/seq/event-data-ctl.c
- src/seq/event-data-note.c
- src/seq/event-data-queue.c
- src/seq/event-data-result.c
- src/seq/event-fixed.c
- src/seq/event-variable.c
- src/seq/event.c
- src/seq/port-info.c
- src/seq/query.c
- src/seq/queue-info.c
- src/seq/queue-status.c
- src/seq/queue-tempo.c
- src/seq/queue-timer-alsa.c
- src/seq/queue-timer.c
- src/seq/remove-filter.c
- src/seq/subscribe-data.c
- src/seq/system-info.c
- src/seq/tstamp.c
- src/seq/user-client.c
This patch fulfills documentation for ALSASeq.
> alsa-gobject: seq: fulfill documentation for ALSASeq

- doc/reference/hwdep/alsahwdep-docs.xml
A commit eb03ec0340b ("hwdep: fulfill documentation for ALSAHwdep") fulfilled documentation for ALSAHwDep but the content of introduction element is missing.
This patch fixes it.
> alsa-gobject: doc: hwdep: fix missing content of introduction element

- src/timer/alsatimer.map
- src/timer/query.c
- src/timer/query.h
ALSA snd_timer kernel module has a parameter for source of timestamping. Applications cannot refer to the parameter via UAPI of Linux kernel, however it's possible via sysfs.
This patch adds an API to refer to the parameter.
> alsa-gobject: timer: add global method to retrieve current source of timestamp

- src/seq/meson.build
- src/seq/query.c
- src/timer/meson.build
- tests/alsaseq-queue-timer
- tests/meson.build
This patchset includes misc fixes for ALSASeq.
Especially the execution of g-ir-scanner to generate ALSASeq-0.0 becomes to expect ALSATimer-0.0 is available. Although it is expected, it results in Python 3 gir loader (PyGObject) loading ALSATimer-0.0 before loading ALSASeq-0.0. Any test for ALSASeq-0.0 is going to fail because ALSATimer-0.0 is not available before installing. To solve the issue, the patchset includes the patch to change test procedure to arrange environment variables.
> alsa-gobject: seq: misc fixes (take 2)

- src/ctl/elem-info.c
- src/timer/alsatimer.map
- src/timer/user-instance.c
- src/timer/user-instance.h
- tests/alsatimer-user-instance
Currently ALSATimer.UserInstance has any attach API to decide the type of
event to read. In design of ALSA Timer core, the attach API has two
functionality; to attach or to detach with error for absent timer device.
Current implementation has inconvenient for the functionality due to
execution to choose the type of event in advance. The execution fails
when the instance is already attached.
This commit adds a new API to choose the type of event and split the
call from any attach API.
> alsa-gobject: timer: user_instance: add API to choose the type of event to read

- src/rawmidi/substream-status.c
- src/seq/alsaseq.map
- src/seq/client-info.c
- src/seq/port-info.c
- src/seq/user-client.c
- src/seq/user-client.h
- tests/alsaseq-user-client
ALSASeq.UserClient.create_port() has nullable argument for the numerical ID of port to use SNDRV_SEQ_PORT_FLG_GIVEN_PORT flag properly. However, the nullable is not inconvenient for PyGObject and causes SIGSEGV.
This patchset adds an alternative API, ALSASeq.UserClient.create_port_at() for the flag, then ALSASeq.UserClient.create_port() hs no argument for explicit port ID.
Additionally, this patchset includes some fixes for the other parts.
> alsa-gobject: seq: fix port creation API

- src/seq/query.c
- src/seq/query.h
- src/timer/query.c
- src/timer/query.h
- src/timer/user-instance.c
- src/timer/user-instance.h
It's probable to retrieve status for something several times in runtime, and it's convenient for the runtime to use pre-allocated instance for the status.
> alsa-gobject: seq/timer: use (inout) annotation for API to retrieve status

- src/seq/alsaseq.map
- src/seq/queue-status.c
- src/seq/queue-status.h
- src/timer/alsatimer.map
- src/timer/device-status.c
- src/timer/device-status.h
- src/timer/instance-status.c
- src/timer/instance-status.h
- tests/alsaseq-queue-status
- tests/alsatimer-device-status
- tests/alsatimer-instance-status
In patchset at #38, I forgot to add constructors for issued status object because no function call returns the instance of object. This patchset adds the constructors.
> alsa-gobject: seq/timer: add constructure for status object

- src/seq/event-data-connect.c
- src/seq/event-data-connect.h
- src/seq/event-data-ctl.c
- src/seq/event-data-ctl.h
- src/seq/event-data-note.c
- src/seq/event-data-note.h
- src/seq/event-data-queue.c
- src/seq/event-data-queue.h
- src/seq/event-data-result.c
- src/seq/event-data-result.h
- src/seq/queue-timer-data-alsa.c
- src/seq/queue-timer-data-alsa.h
- src/seq/tstamp.c
- src/seq/tstamp.h
- src/timer/event-data-tick.c
- src/timer/event-data-tick.h
- src/timer/event-data-tstamp.c
- src/timer/event-data-tstamp.h
In ALSATimer and ALSASeq, some methods have prototype such that self argument don't have const qualifier even if it's getter method.
This patchset adds const qualifier to the methods.
> alsa-gobject: timer/seq: use const qualifier to self argument for getter API

- src/seq/client-info.c
- src/seq/client-pool.c
- src/seq/query.c
- src/seq/query.h
- src/seq/queue-info.c
- src/seq/queue-status.c
- src/seq/queue-tempo.c
- src/seq/queue-timer.c
- src/seq/user-client.c
- src/seq/user-client.h
In ALSA Sequencer core, the number of client/port/queue is defined as below per each:
- SNDRV_SEQ_MAX_CLIENTS (=192)
- SNDRV_SEQ_MAX_PORTS (=254)
- SNDRV_SEQ_MAX_QUEUES (=32)
Following to it, in UAPI of Linux sound subsystem, several structures have `unsigned char` type of members:
- struct snd_seq_addr.client
- struct snd_seq_addr.port
- struct snd_seq_event.queue
On the other hand, within the UAPI, 'int' type is also used for the numerical ID of client/port/queue. Following to the 'int' type, current API of ALSASeq includes API with 'gint' or 'guint' type of argument. However, it's better to use 'guint8' with consideration about the range of value.
This patchset declares the arguments to have 'guint8' type.
> alsa-gobject: seq: use guint8 for the numerical ID of client/port/queue

- src/seq/query.c
- src/seq/query.h
Some APIs are missing in #41. This patchset has supplements for them.
> alsa-gobject: supplement to use guint8 for the numerical ID of client/queue

- src/ctl/elem-value.c
- src/rawmidi/alsarawmidi-enum-types.h
- src/rawmidi/stream-pair.h
- src/seq/client-pool.c
- src/seq/event-cntr.h
- src/seq/query.h
- src/seq/remove-filter.h
- src/seq/user-client.c
- src/timer/instance-params.c
This patchset is trivial to apply fixes for 4-spaces indentation.
> alsa-gobject: fix indentation

- src/ctl/alsactl.map
- src/ctl/card.c
- src/ctl/card.h
- src/rawmidi/alsarawmidi.map
- src/rawmidi/stream-pair.c
- src/rawmidi/stream-pair.h
- src/seq/alsaseq.map
- src/seq/user-client.c
- src/seq/user-client.h
- src/timer/alsatimer.map
- src/timer/user-instance.c
- src/timer/user-instance.h
- tests/alsactl-card
- tests/alsarawmidi-stream-pair
- tests/alsaseq-user-client
- tests/alsatimer-user-instance
In UAPI of Linux sound subsystem, interfaces support protocol versioning. This patchset adds API to get current protocol version in each interface.
> alsa-gobject: add API to get current protocol version in each interface

- README.rst
- doc/reference/seq/alsaseq-docs.xml
- doc/reference/timer/alsatimer-docs.xml
For better documentation, this patchset reorders sections of ALSATimer/ALSASeq documentation.
> alsa-gobject: reorder documentation sections

- meson.build
This patch is a preparation for official v0.1.0 release. After merged, I'm going to push a tag 'v0.1.0' with release note.
> alsa-gobject: bump version up to 0.1.0 for official release

- src/ctl/alsactl-enum-types.h
- src/ctl/alsactl.map
- src/ctl/card.c
- src/ctl/card.h
- src/ctl/elem-id.c
- src/ctl/elem-info.c
- src/ctl/elem-value.c
- src/ctl/privates.h
- src/ctl/query.c
- tests/alsactl-enums
Current implementation uses library-wide error domain to report error, however this is partly against rule of GError usage. Furthermore, the error delivers information just about errno and hard to know the cause of error.
This patchset enhances error reporting. The library-wide error domain is obsoleted. A new error domain is added just for ALSACtl.Card. The error domain delivers information about the cause of error.
> ctl: enhancement for error reporting

- src/timer/alsatimer-enum-types.h
- src/timer/alsatimer.map
- src/timer/instance-params.c
- src/timer/instance-status.c
- src/timer/privates.h
- src/timer/query.c
- src/timer/user-instance.c
- src/timer/user-instance.h
- tests/alsatimer-enums
The patchset is a part of work about #47.
Current implementation uses library-wide error domain to report error. this
is partly against rule of GError usage. Furthermore, the error delivers
information just about errno and hard to know the cause of error.
This patchset enhances error reporting. The library-wide error domain is
obsoleted. A new error domain is added just for ALSATimer.UserInstance.
The error domain delivers information about the cause of error.
```
Takashi Sakamoto (16):
timer: user_instance: fix function comment
timer: skip check of return value from g_malloc()
timer: check whether method argument for GError is available
timer: add checks for method arguments
timer: instance-params: add checks for method arguments
timer: user_instance: just return when character device is …
```
> [PATCH 00/16] alsa-gobject: timer: enhancement for error reporting

- src/seq/alsaseq-enum-types.h
- src/seq/alsaseq.map
- src/seq/client-info.c
- src/seq/event-cntr.c
- src/seq/privates.h
- src/seq/query.c
- src/seq/queue-status.c
- src/seq/queue-tempo.c
- src/seq/queue-timer.c
- src/seq/remove-filter.c
- src/seq/user-client.c
- src/seq/user-client.h
- tests/alsaseq-enums
The patchset is the part of work about #47.
Current implementation uses library-wide error domain to report error. this
is partly against rule of GError usage. Furthermore, the error delivers
information just about errno and hard to know the cause of error.
This patchset enhances error reporting. The library-wide error domain is
obsoleted. A new error domain is added just for ALSASeq.UserClient.
The error domain delivers information about the cause of error.
```
Takashi Sakamoto (15):
seq: skip check of return value from g_malloc()
seq: check whether method argument for GError is available
seq: add checks for method arguments
seq: user_client: just return when character device is not opened
seq: add GLib enumeration to report type of error for ALSASeq.UserClient
seq: user_client: add …
```
> [PATCH 00/15] alsa-gobject: seq: enhancement for error reporting

- src/ctl/query.c
- src/hwdep/privates.h
- src/hwdep/query.c
- src/seq/query.c
- src/timer/instance-params.c
The patchset is the part of work about #47.
Current implementation uses library-wide error domain to report error. this
is partly against rule of GError usage. Furthermore, the error delivers
information just about errno and hard to know the cause of error.
This patchset enhances error reporting. The library-wide error domain is
obsoleted. ALSAHwdep library is small and includes global functions.
GFileError is used for the functions to report error since It has no
specific error domain in current design.
```
Takashi Sakamoto (9):
seq: query: remove duplicated semicolon
ctl: query: simplify count check
timer: instance_param: simplify count check
hwdep: skip check of return value from g_malloc()
hwdep: check whether method argument for GError is available
hwdep: add checks for method …
```
> [PATCH 0/9] alsa-gobject: hwdep: enhancement for error reporting

- src/rawmidi/alsarawmidi-enum-types.h
- src/rawmidi/alsarawmidi.map
- src/rawmidi/privates.h
- src/rawmidi/query.c
- src/rawmidi/stream-pair.c
- src/rawmidi/stream-pair.h
- src/seq/user-client.c
- src/timer/user-instance.c
- tests/alsarawmidi-enums
The patchset is the part of work about #47.
Current implementation uses library-wide error domain to report error. this
is partly against rule of GError usage. Furthermore, the error delivers
information just about errno and hard to know the cause of error.
This patchset enhances error reporting. The library-wide error domain is
obsoleted. A new error domain is added just for ALSARawmidi.StreamPair.
The error domain delivers information about the cause of error
```
Takashi Sakamoto (15):
timer: user_instance: fix code for GFileError
seq: user_client: fix code for GFileError
rawmidi: skip check of return value from g_malloc()
rawmidi: check whether method argument for GError is available
rawmidi: add checks for method arguments
rawmidi: stream_pair: just return when character device is not …
```
> [PATCH 00/15] alsa-gobject: rawmidi: enhancement for error reporting

- src/rawmidi/privates.h
- src/rawmidi/query.c
- src/rawmidi/stream-pair.c
This patchset fixes #53 .
ALSARawmidi.StreamPair.open() has `subdevice_id` argument to select
one of substreams supported by the Rawmidi device. However, this
parameter is ignored and the first substream is always selected.
In ALSA rawmidi core, private structure associated to file descriptor
to control character device assists selection of rawmidi substream.
It requires to keep the file descriptor until the selected substream
is actually attached by open rawmidi character device.
Current implementation of libalsarawmidi is to close the file descriptor
before opening rawmidi character device. This is the cause of the issue.
This commit fixes the bug by keeping the file descriptor till opening
rawmidi character device.
```
Takashi Sakamoto (2):
rawmidi: query: allow caller to take …
```
> [PATCH 0/2] alsa-gobject: rawmidi: fix to select substream

- src/ctl/alsactl.map
- src/ctl/card.c
- src/ctl/card.h
In ALSA control interface, the data of TLV (Type-Length-Value) style is
defined as array with unsigned int type of element. However, current
implementation of ALSACtl.Card handles them as signed int type.
This commit fixes the bug. This loses backward compatibility to v0.1.0
in a point of type of function argument.
> [PATCH] alsa-gobject: ctl: change prototype of function relevant to TLV

- src/ctl/query.c
- src/hwdep/query.c
- src/rawmidi/query.c
- src/rawmidi/stream-pair.c
- src/seq/query.c
- src/timer/device-id.c
- src/timer/query.c
- src/timer/user-instance.c
This patchset includes various fixes toward v0.2.0 release.
```
Takashi Sakamoto (10):
timer: device_id: fix function comment
timer: user_instance: fix function comment
rawmidi: stream_pair: update function comment for error reporting
hwdep: query: fix usage of uninitialized value
rawmidi: query: fix usage of uninitialized value
ctl: query: fulfil comment about GError
timer: query: fulfil comment about GError
seq: query: fulfil comment about GError
hwdep: query: fulfil comment about GError
rawmidi: query: fulfil comment about GError
src/ctl/query.c           |  8 ++++----
src/hwdep/query.c         | 10 +++++-----
src/rawmidi/query.c       | 12 ++++++------
src/rawmidi/stream-pair.c | 23 ++++++++++++++---------
src/seq/query.c           | 26 +++++++++++++-------------
src/timer/device-id.c …
```
> alsa-gobject: various fixes

- src/hwdep/alsahwdep-enum-types.h
- src/seq/client-info.c
Some users would like to build alsa-gobject in former versions of Linux kernel.
https://sourceforge.net/p/alsa/mailman/alsa-user/thread/d95fce3f-5244-0e5f-4a5f-fece9b853307%40sakamocchi.jp/#msg35839069
This patchset use some macro from Linux kernel for conditional build
```
Takashi Sakamoto (3):
seq: client_info: conditional build for Linux kernel v4.6 or later
hwdep: conditional build for Linux kernel v4.9 or later
hwdep: conditional build for Linux kernel 4.12 or later
src/hwdep/alsahwdep-enum-types.h | 16 +++++++++++++---
src/seq/client-info.c            |  9 +++++++--
2 files changed, 20 insertions(+), 5 deletions(-)
```
> [PATCH 0/3] alsa-gobject: buildable in kernel 4.5 or later

- .github/workflows/build.yml
- README.rst
This patchset fixes some bugs below:
* Ubuntu 19.10/i386 is EOL and no release is available for i386 architecture in Ubuntu project
* Update Fedora version for CI environment
* Wrong command is in install section of README
```
Takashi Sakamoto (3):
correct install section in README
fix workflow according to EOF of i386 ubuntu distribution
update Fedora release for CI environment
.github/workflows/build.yml | 83 +++++++++++++++++++------------------
README.rst                  |  2 +-
2 files changed, 43 insertions(+), 42 deletions(-)
```
> [PATCH 0/3] alsa-gobject: misc fixes

- src/ctl/query.c
- src/hwdep/query.c
- src/rawmidi/query.c
- src/seq/client-info.c
- src/seq/port-info.c
- src/seq/query.c
- src/seq/queue-info.c
Current implementation of libalsactl0, libalsarawmidi0, and libalsahwdep0 includes trivial bugs such as usage of uninitialized local variable. This patchset fixes the bugs.
```
Takashi Sakamoto (2):
ctl/rawmidi/hwdep: fix compiler warning due to uninitialized variables
seq: use safer way to copy strings
src/ctl/query.c       | 4 ++--
src/hwdep/query.c     | 4 ++--
src/rawmidi/query.c   | 4 ++--
src/seq/client-info.c | 2 +-
src/seq/port-info.c   | 2 +-
src/seq/query.c       | 2 +-
src/seq/queue-info.c  | 2 +-
7 files changed, 10 insertions(+), 10 deletions(-)
```
> [PATCH 0/2] ctl/rawmidi/hwdep: fix trivial bugs

- src/ctl/elem-id.c
- src/ctl/query.c
- src/hwdep/query.c
- src/rawmidi/query.c
- src/seq/addr.c
- src/seq/event-data-connect.c
- src/seq/event-data-ctl.c
- src/seq/event-data-note.c
- src/seq/event-data-queue.c
- src/seq/event-data-result.c
- src/seq/queue-timer-data-alsa.c
- src/seq/remove-filter.c
- src/seq/tstamp.c
- src/timer/device-id.c
- src/timer/event-data-tick.c
- src/timer/event-data-tstamp.c
- src/timer/event.c
The v0.2.1 release includes misfunction of ALSACtl.Card.get_elem_id_list(). This patchset includes fix for it as well as arrangement for GLib 2.0 v2.68.
```
Takashi Sakamoto (3):
ctl/hwdep/rawmidi: fix uninitialized warning
ctl/timer/seq: optimization for GLib v2.68
ctl: fix misfunction of alsactl_get_card_id_list()
src/ctl/elem-id.c               | 10 +++++++++-
src/ctl/query.c                 |  2 +-
src/hwdep/query.c               |  2 +-
src/rawmidi/query.c             |  2 +-
src/seq/addr.c                  | 10 +++++++++-
src/seq/event-data-connect.c    | 10 +++++++++-
src/seq/event-data-ctl.c        | 10 +++++++++-
src/seq/event-data-note.c       | 10 +++++++++-
src/seq/event-data-queue.c      | 10 +++++++++-
src/seq/event-data-result.c     | 10 +++++++++- …
```
> [PATCH 0/3] fix v0.2.1

- src/rawmidi/query.c
- src/rawmidi/query.h
- src/seq/meson.build
This patchset fixes unintended two items below.
* argument name against convention in this project
* line break inner identifier in meson.build
```
Takashi Sakamoto (2):
rawmidi: fix argument names with suffix '_id'
meson: fix unintended line break for identifier
src/rawmidi/query.c | 12 ++++++------
src/rawmidi/query.h |  2 +-
src/seq/meson.build |  3 +--
3 files changed, 8 insertions(+), 9 deletions(-)
```
> [PATCH 0/2] rawmidi/meson: fix miscellaneous bugs

- meson.build
- src/ctl/meson.build
- src/hwdep/meson.build
- src/meson.build
- src/rawmidi/meson.build
- src/seq/meson.build
- src/timer/meson.build
In this project, meson configuration for included libraries consists of
two parts; common and specific. During development, the common part
gains differences between libraries. This patchset refactors meson
configuration to increase the same expression in the common part.
```
Takashi Sakamoto (7):
timer: code refactoring for search path of alsatimer header
meson: aggregate dependency declaration on glib/gobject and libudev
meson: aggregate module imports
meson: fulfill missing sources for gir scanner which are blank
meson: move pkg-config description to metadata part
meson: aggregate and move extra gir to metadata part
meson: move path to top header to metadata part
meson.build             |  2 --
src/ctl/meson.build     | 37 +++++++++++++++-------------------
src/hwdep/meson.build   | 39 …
```
> [PATCH 0/7] meson: refactor common part of configuration 

- src/ctl/card.c
- src/ctl/meson.build
- src/ctl/query.c
- src/hwdep/meson.build
- src/hwdep/query.c
- src/meson.build
- src/rawmidi/meson.build
- src/rawmidi/query.c
- src/rawmidi/stream-pair.c
- src/seq/meson.build
- src/seq/query.c
- src/seq/user-client.c
- src/timer/meson.build
- src/timer/query.c
- src/timer/user-instance.c
- src/utils/ioctl.c
- src/utils/meson.build
- src/utils/string.c
- src/utils/sysfs.c
- src/utils/utils.h
Current implementation of included libraries have duplicated codes
to operate over sysfs by libudev and so. It's inconvenient in a point of
maintenance.
This patchset adds internal static library to include such codes.
```
Takashi Sakamoto (6):
utils: build internal static library including common utilities
utils: add utility to compute integer value from string literal
utils: add utilities to allocate string information for device
utils: add utilitiy to generate list of sysnum by prefix of sysname
utils: add utilities to request control ioctl
utils: add utility macros to generate GError with file domain
src/ctl/card.c            |   5 +-
src/ctl/meson.build       |   2 +-
src/ctl/query.c           | 261 ++----------------------------
src/hwdep/meson.build     |   2 +-
src/hwdep/query.c …
```
> [PATCH 0/6] add internal static library to include common utilities

- src/seq/query.c
- src/timer/query.c
It looks like errno.h has to be included explicitly when compiling with older
gcc versions. This issue was encountered on the following system:
- Ubuntu 20.04 LTS
- Linux 5.4.0-156
- gcc 10.5.0
- Meson 0.53.2
> Fix 'errno undeclared' compile error with older gcc versions

- src/ctl/elem-info-common.c
- src/ctl/elem-info-enumerated.c
- src/ctl/elem-info-integer.c
- src/ctl/elem-info-integer64.c
- src/ctl/elem-info-single-array.c
- src/hwdep/device-common.c
- src/seq/port-info.c
- src/seq/queue-timer-alsa.c
- src/seq/queue-timer-common.c
- src/seq/remove-filter.c
- src/seq/subscribe-data.c
The version of gi-docgen applies the restrict rule for the version expression. In the rule, the dot following to the number causes failure.
The series of changes in this MR solves the failure.
> ctl/hwdep/seq: optimize to gi-docgen 2023.3 or later
